### ISSUE TITLE
High conversion rates in smallRNA control samples 

### ISSUE THREAD

**Issue by Enidanellani** [t-neumann/slamdunk#67]
Dear Tobias,
I was trying to run the slamdunk all pipeline on the samples of Reichholf et al (MolCell, 2019) to see how it deals with small RNA sequencing.  
However, the first thing I noticed when running alleyoop rates on the filtered bam files, was that the T>C (+strand) or A>G (-strand) conversion rates don’t differ much between the control samples (no s4U unoxidized: 3-4%, +s4U unoxidized: 5-6%) and the s4U containing sample (+s4U oxidized: 6%).  
[Reichholff_conversion_rates.pdf](https://github.com/t-neumann/slamdunk/files/4130785/Reichholff_conversion_rates.pdf)
I am aware that these rates concern the whole genome, but I would expect the control samples conversion rates to be close to 0? What am I missing?
Thank you so much for your help!
Best wishes,
Nina

**Comment by t-neumann** [comment]
Hi Nina,

the data analysis for the small RNA sequencing paper was entirely handled by its first-author (Brian). Afaik he did not use Slamdunk at all for his analysis due to the specifics of small RNAs, but mostly bowtie.

He has the pipeline he used on Github:

https://github.com/AmeresLab/smRNAseq

And there's also a detailled description in the methods section. I can also put you in touch with him directly if you want, but I don't feel like this is an issue of Slamdunk and thus would close it if you are ok with that?

**Comment by Enidanellani** [comment]
Hello!
Thanks for your answer and your link. I was indeed aware of that and just testing whether slamdunk was also suitable. 
I'll close the conversation.
Thank you and best wishes,
Nina
