### ISSUE TITLE
Multimapper-Reassignment Stragety

### ISSUE THREAD

**Issue by iris-summer** [t-neumann/slamdunk#83]
Hi Tobias,

I'm a super new learner in bioinformatics. I know the SLAMdunk designed for 3'UTR so any additional alignments to non-UTR regions have been removed. However, in our case, we'd like to keep the exon region in the filtered_bam file as well. Is there a way to do it?

Best,
Iris

**Comment by t-neumann** [comment]
Hi Iris,

so Slamdunk quantifies T>C reads and conversions within a bed files. For Quantseq, 3' ends are amplified, so usually you deliver the 3' UTR file you mentioned to quantify your reads there. But in principal you can supply any coordinates in the bed file you want, also the exon regions you were talking about.

The only thing were reads are filtered is for multimapping reads - i.e. reads that map to multiple positions in your genome equally well (usually repetitive regions). Here you can tell Slamdunk to only retain those multimappers, that map unambiguously to a region in your bed file (again usually 3' UTRs) and otherwise only have alignments to regions not contained in your bed file (e.g. non-UTR regions).

As I said, this constraint is only for multimapping reads and also can be controlled by the bed-file you supply, but in principal there is no real constraint to which regions you used for T>C read quantification, since Slamdunk blindly takes the supplied regions in your bed file which could be anything, from 3' UTRs to exons or other genomic regions.

Best,

Tobi

**Comment by iris-summer** [comment]
Thanks so much for your relpy, Tobi! 

I did use the whole genome bed.file as annotation file. Some of the mature transcripts were filtered out and only the 3'-UTR left. If the reads can map to several varients of one gene body, such as snRNA U1, would SLAMDUNK remove all of these reads as multimapping reads? 

Best,
Iris

**Comment by t-neumann** [comment]
Yes those would then be filtered out for sure
